import { ModelAnalysis, ModelConfig, HardwareSpec } from '../types/model';

interface ExportData {
  analysis: ModelAnalysis;
  config: ModelConfig;
  selectedHardware?: HardwareSpec;
  timestamp: string;
}

export function formatMemoryForExport(bytes: number): string {
  if (bytes === 0) return '0 B';
  
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  const k = 1024;
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + units[i];
}

export function formatParametersForExport(params: number): string {
  if (params === 0) return '0';
  
  const units = ['', 'K', 'M', 'B', 'T'];
  const k = 1000;
  const i = Math.floor(Math.log(Math.abs(params)) / Math.log(k));
  
  if (i === 0) return params.toString();
  
  return parseFloat((params / Math.pow(k, i)).toFixed(2)) + units[i];
}

export function generateMarkdownReport(data: ExportData): string {
  const { analysis, config, selectedHardware, timestamp } = data;
  
  const md = `# PyTorch Model Analysis Report

**Generated:** ${new Date(timestamp).toLocaleString()}

## Model Overview

- **Total Parameters:** ${formatParametersForExport(analysis.totalParams)} (${analysis.totalParams.toLocaleString()})
- **Memory Footprint:** ${formatMemoryForExport(analysis.memoryFootprint.total)}
- **Input Shape:** [${analysis.inputShape.join(', ')}]

## Configuration

- **Precision:** ${config.precision.label}
- **Mode:** ${config.mode}
- **Batch Size:** ${config.batchSize}

## Memory Breakdown

| Component | Size | Percentage |
|-----------|------|------------|
| Weights | ${formatMemoryForExport(analysis.memoryFootprint.weights)} | ${((analysis.memoryFootprint.weights / analysis.memoryFootprint.total) * 100).toFixed(1)}% |
| Activations | ${formatMemoryForExport(analysis.memoryFootprint.activations)} | ${((analysis.memoryFootprint.activations / analysis.memoryFootprint.total) * 100).toFixed(1)}% |
${config.mode === 'training' ? `| Training Overhead | ${formatMemoryForExport(analysis.memoryFootprint.total - analysis.memoryFootprint.weights - analysis.memoryFootprint.activations)} | ${(((analysis.memoryFootprint.total - analysis.memoryFootprint.weights - analysis.memoryFootprint.activations) / analysis.memoryFootprint.total) * 100).toFixed(1)}% |` : ''}
| **Total** | **${formatMemoryForExport(analysis.memoryFootprint.total)}** | **100%** |

## Layer Breakdown

| Layer Name | Type | Shape | Parameters | % of Total |
|------------|------|-------|------------|------------|
${analysis.layers.map(layer => {
  const percentage = analysis.totalParams > 0 ? (layer.parameters / analysis.totalParams) * 100 : 0;
  const shapeStr = layer.shape.length > 0 ? `[${layer.shape.join(', ')}]` : '-';
  return `| ${layer.name} | ${layer.type.replace('nn.', '')} | ${shapeStr} | ${formatParametersForExport(layer.parameters)} | ${percentage.toFixed(1)}% |`;
}).join('\n')}
| **Total** | | | **${formatParametersForExport(analysis.totalParams)}** | **100%** |

${selectedHardware ? `
## Selected Hardware

- **Device:** ${selectedHardware.name}
- **VRAM:** ${selectedHardware.vram}GB
- **Memory Bandwidth:** ${selectedHardware.memoryBandwidth} GB/s
- **Category:** ${selectedHardware.category}
- **Memory Utilization:** ${(((analysis.memoryFootprint.total / (1024 ** 3)) / selectedHardware.vram) * 100).toFixed(1)}%
- **Available After Load:** ${formatMemoryForExport(Math.max(0, (selectedHardware.vram * 1024 ** 3) - analysis.memoryFootprint.total))}
` : ''}

## Technical Details

- **Bytes per Parameter:** ${config.precision.bytesPerParam}
- **Total Layers:** ${analysis.layers.length}
${config.mode === 'training' ? `- **Training Mode:** Includes gradients and optimizer states (Adam optimizer assumed)` : ''}

---

*Generated by Layer Lens - PyTorch Model Analyzer*  
*All processing performed locally in browser for privacy*
`;

  return md.trim();
}

export function generateJSONReport(data: ExportData): string {
  return JSON.stringify(data, null, 2);
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportMarkdown(
  analysis: ModelAnalysis,
  config: ModelConfig,
  selectedHardware?: HardwareSpec
) {
  const data: ExportData = {
    analysis,
    config,
    selectedHardware,
    timestamp: new Date().toISOString()
  };
  
  const markdown = generateMarkdownReport(data);
  const filename = `model-analysis-${new Date().toISOString().split('T')[0]}.md`;
  
  downloadFile(markdown, filename, 'text/markdown');
}

export function exportJSON(
  analysis: ModelAnalysis,
  config: ModelConfig,
  selectedHardware?: HardwareSpec
) {
  const data: ExportData = {
    analysis,
    config,
    selectedHardware,
    timestamp: new Date().toISOString()
  };
  
  const json = generateJSONReport(data);
  const filename = `model-analysis-${new Date().toISOString().split('T')[0]}.json`;
  
  downloadFile(json, filename, 'application/json');
}